"""
Seed data for LaptopMind — 20 laptops spanning RTX 30, 40, and 50 series.
All store URLs use product-specific search pages (not homepages).
"""

import datetime
import random
from database import SessionLocal, engine, Base
from models import Laptop, StorePrice, PriceHistory

Base.metadata.create_all(bind=engine)

LAPTOPS = [
    # ── RTX 30-series ──────────────────────────────────────────────────────────
    {
        "brand": "ASUS",
        "name": "ASUS TUF Gaming F15 (RTX 3050)",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80",
        "cpu": "Intel Core i5-12500H",
        "cpu_score": 72,
        "gpu": "NVIDIA RTX 3050",
        "gpu_score": 58,
        "ram_gb": 8,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "IPS",
        "refresh_rate": 144,
        "weight_kg": 2.3,
        "battery_wh": 90,
        "battery_score": 62,
        "thermal_score": 70,
        "base_price": 54999,
        "description": "A solid entry-level gaming laptop with RTX 3050 for 1080p gaming, a 144Hz display, and a large 90Wh battery.",
        "stores": [
            {"store": "Amazon",          "price": 49999,  "url": "https://www.amazon.in/s?k=ASUS+TUF+Gaming+F15+RTX+3050&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 51999,  "url": "https://www.flipkart.com/search?q=ASUS+TUF+F15+RTX+3050"},
            {"store": "Croma",           "price": 54999,  "url": "https://www.croma.com/searchB?q=ASUS+TUF+F15+RTX+3050"},
            {"store": "Reliance Digital","price": 53499,  "url": "https://www.reliancedigital.in/search?q=ASUS+TUF+F15+RTX+3050"},
            {"store": "ASUS Store",      "price": 54999,  "url": "https://www.asus.com/in/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-f15/"},
        ],
    },
    {
        "brand": "Lenovo",
        "name": "Lenovo IdeaPad Gaming 3 (RTX 3060)",
        "image_url": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
        "cpu": "AMD Ryzen 5 6600H",
        "cpu_score": 76,
        "gpu": "NVIDIA RTX 3060",
        "gpu_score": 68,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "IPS",
        "refresh_rate": 120,
        "weight_kg": 2.4,
        "battery_wh": 60,
        "battery_score": 50,
        "thermal_score": 68,
        "base_price": 64999,
        "description": "Lenovo IdeaPad Gaming 3 with RTX 3060 delivers great 1080p gaming performance at a budget-friendly price backed by Ryzen 5.",
        "stores": [
            {"store": "Amazon",          "price": 59999,  "url": "https://www.amazon.in/s?k=Lenovo+IdeaPad+Gaming+3+RTX+3060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 61999,  "url": "https://www.flipkart.com/search?q=Lenovo+IdeaPad+Gaming+3+RTX+3060"},
            {"store": "Croma",           "price": 64999,  "url": "https://www.croma.com/searchB?q=Lenovo+IdeaPad+Gaming+3+RTX+3060"},
            {"store": "Reliance Digital","price": 63499,  "url": "https://www.reliancedigital.in/search?q=Lenovo+IdeaPad+Gaming+3+RTX+3060"},
            {"store": "Lenovo Store",    "price": 64999,  "url": "https://www.lenovo.com/in/en/laptops/ideapad/ideapad-gaming-3/"},
        ],
    },
    # ── RTX 40-series ──────────────────────────────────────────────────────────
    # Lenovo LOQ series (hugely popular in India)
    {
        "brand": "Lenovo",
        "name": "Lenovo LOQ 15 Gen 3 (RTX 4050)",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
        "cpu": "AMD Ryzen 5 7640HS",
        "cpu_score": 78,
        "gpu": "NVIDIA RTX 4050",
        "gpu_score": 75,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "IPS",
        "refresh_rate": 144,
        "weight_kg": 2.4,
        "battery_wh": 60,
        "battery_score": 48,
        "thermal_score": 74,
        "base_price": 72999,
        "description": "The Lenovo LOQ 15 Gen 3 is a value-focused gaming laptop with Ryzen 5 and RTX 4050, delivering solid 1080p gaming performance at an aggressive price.",
        "stores": [
            {"store": "Amazon",          "price": 68999,  "url": "https://www.amazon.in/s?k=Lenovo+LOQ+15+Gen+3+RTX+4050&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 69999,  "url": "https://www.flipkart.com/search?q=Lenovo+LOQ+15+Gen+3+RTX+4050"},
            {"store": "Croma",           "price": 72999,  "url": "https://www.croma.com/searchB?q=Lenovo+LOQ+15+RTX+4050"},
            {"store": "Reliance Digital","price": 71499,  "url": "https://www.reliancedigital.in/search?q=Lenovo+LOQ+15+RTX+4050"},
            {"store": "Lenovo Store",    "price": 72999,  "url": "https://www.lenovo.com/in/en/laptops/loq/loq-15/"},
        ],
    },
    {
        "brand": "Lenovo",
        "name": "Lenovo LOQ 15 Gen 3 (RTX 4060)",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
        "cpu": "Intel Core i5-13450HX",
        "cpu_score": 80,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "IPS",
        "refresh_rate": 144,
        "weight_kg": 2.4,
        "battery_wh": 60,
        "battery_score": 46,
        "thermal_score": 76,
        "base_price": 84999,
        "description": "Lenovo LOQ 15 Gen 3 with Intel Core i5 and RTX 4060 is one of the best value gaming laptops available — excellent 1080p gaming at a budget-friendly price.",
        "stores": [
            {"store": "Amazon",          "price": 79999,  "url": "https://www.amazon.in/s?k=Lenovo+LOQ+15+Gen+3+RTX+4060+Intel&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 81999,  "url": "https://www.flipkart.com/search?q=Lenovo+LOQ+15+Gen+3+RTX+4060"},
            {"store": "Croma",           "price": 84999,  "url": "https://www.croma.com/searchB?q=Lenovo+LOQ+15+RTX+4060"},
            {"store": "Reliance Digital","price": 82999,  "url": "https://www.reliancedigital.in/search?q=Lenovo+LOQ+15+RTX+4060"},
            {"store": "Lenovo Store",    "price": 84999,  "url": "https://www.lenovo.com/in/en/laptops/loq/loq-15/"},
        ],
    },
    {
        "brand": "Lenovo",
        "name": "Lenovo LOQ 16 Gen 1 (RTX 4070)",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
        "cpu": "Intel Core i7-13650HX",
        "cpu_score": 86,
        "gpu": "NVIDIA RTX 4070",
        "gpu_score": 90,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 16.0,
        "display_type": "IPS",
        "refresh_rate": 165,
        "weight_kg": 2.5,
        "battery_wh": 80,
        "battery_score": 50,
        "thermal_score": 78,
        "base_price": 114999,
        "description": "The Lenovo LOQ 16 with RTX 4070 steps up to high-refresh gaming with a 165Hz display and powerful GPU, offering great 1440p gaming performance at a competitive price.",
        "stores": [
            {"store": "Amazon",          "price": 107999, "url": "https://www.amazon.in/s?k=Lenovo+LOQ+16+RTX+4070&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 109999, "url": "https://www.flipkart.com/search?q=Lenovo+LOQ+16+RTX+4070"},
            {"store": "Croma",           "price": 114999, "url": "https://www.croma.com/searchB?q=Lenovo+LOQ+16+RTX+4070"},
            {"store": "Reliance Digital","price": 111999, "url": "https://www.reliancedigital.in/search?q=Lenovo+LOQ+16+RTX+4070"},
            {"store": "Lenovo Store",    "price": 114999, "url": "https://www.lenovo.com/in/en/laptops/loq/loq-16/"},
        ],
    },
    # HP Omen series
    {
        "brand": "HP",
        "name": "HP Omen 16 (RTX 4060)",
        "image_url": "https://images.unsplash.com/photo-1553355552-9808ef857c01?w=800&q=80",
        "cpu": "Intel Core i7-13700HX",
        "cpu_score": 87,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 16.1,
        "display_type": "IPS",
        "refresh_rate": 165,
        "weight_kg": 2.35,
        "battery_wh": 83,
        "battery_score": 56,
        "thermal_score": 80,
        "base_price": 109999,
        "description": "HP Omen 16 with RTX 4060 brings serious gaming muscle with a 165Hz IPS display, strong thermals, and Intel i7 — a top pick for competitive gamers on a mid-range budget.",
        "stores": [
            {"store": "Amazon",          "price": 99999,  "url": "https://www.amazon.in/s?k=HP+Omen+16+RTX+4060+2024&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 104999, "url": "https://www.flipkart.com/search?q=HP+Omen+16+RTX+4060"},
            {"store": "Croma",           "price": 109999, "url": "https://www.croma.com/searchB?q=HP+Omen+16+RTX+4060"},
            {"store": "Reliance Digital","price": 106999, "url": "https://www.reliancedigital.in/search?q=HP+Omen+16+RTX+4060"},
            {"store": "HP Store",        "price": 109999, "url": "https://www.hp.com/in-en/shop/pdp/hp-omen-16-wf0028tx"},
        ],
    },
    {
        "brand": "HP",
        "name": "HP Omen 16 (RTX 4070)",
        "image_url": "https://images.unsplash.com/photo-1553355552-9808ef857c01?w=800&q=80",
        "cpu": "Intel Core i9-13900HX",
        "cpu_score": 91,
        "gpu": "NVIDIA RTX 4070",
        "gpu_score": 90,
        "ram_gb": 32,
        "storage_gb": 1024,
        "display_inch": 16.1,
        "display_type": "IPS",
        "refresh_rate": 240,
        "weight_kg": 2.45,
        "battery_wh": 83,
        "battery_score": 54,
        "thermal_score": 82,
        "base_price": 159999,
        "description": "HP Omen 16 RTX 4070 is a powerhouse gaming laptop with i9 processor, 240Hz display, 32GB RAM, and 1TB storage — ready for 1440p gaming and content creation.",
        "stores": [
            {"store": "Amazon",          "price": 149999, "url": "https://www.amazon.in/s?k=HP+Omen+16+RTX+4070+i9&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 154999, "url": "https://www.flipkart.com/search?q=HP+Omen+16+RTX+4070"},
            {"store": "Croma",           "price": 159999, "url": "https://www.croma.com/searchB?q=HP+Omen+16+RTX+4070"},
            {"store": "Reliance Digital","price": 156999, "url": "https://www.reliancedigital.in/search?q=HP+Omen+16+RTX+4070"},
            {"store": "HP Store",        "price": 159999, "url": "https://www.hp.com/in-en/shop/pdp/hp-omen-16-wf0080tx"},
        ],
    },
    # Acer Nitro V (popular budget gaming)
    {
        "brand": "Acer",
        "name": "Acer Nitro V 15 (RTX 4050)",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80",
        "cpu": "Intel Core i5-13420H",
        "cpu_score": 74,
        "gpu": "NVIDIA RTX 4050",
        "gpu_score": 75,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "IPS",
        "refresh_rate": 144,
        "weight_kg": 2.4,
        "battery_wh": 57,
        "battery_score": 46,
        "thermal_score": 72,
        "base_price": 64999,
        "description": "Acer Nitro V 15 is an entry-level gaming laptop with RTX 4050 and Intel Core i5, perfect for students who want to play popular titles on a tight budget.",
        "stores": [
            {"store": "Amazon",          "price": 59999,  "url": "https://www.amazon.in/s?k=Acer+Nitro+V+15+RTX+4050&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 61999,  "url": "https://www.flipkart.com/search?q=Acer+Nitro+V+15+RTX+4050"},
            {"store": "Croma",           "price": 64999,  "url": "https://www.croma.com/searchB?q=Acer+Nitro+V+15+RTX+4050"},
            {"store": "Reliance Digital","price": 63499,  "url": "https://www.reliancedigital.in/search?q=Acer+Nitro+V+15+RTX+4050"},
            {"store": "Acer Store",      "price": 64999,  "url": "https://www.acer.com/in-en/laptops/nitro/nitro-v-15/"},
        ],
    },
    {
        "brand": "Acer",
        "name": "Acer Nitro 16 (RTX 4060)",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80",
        "cpu": "AMD Ryzen 7 7745HX",
        "cpu_score": 84,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 16.0,
        "display_type": "IPS",
        "refresh_rate": 165,
        "weight_kg": 2.5,
        "battery_wh": 76,
        "battery_score": 48,
        "thermal_score": 76,
        "base_price": 89999,
        "description": "Acer Nitro 16 with Ryzen 7 and RTX 4060 is a well-rounded mid-range gaming laptop with a 165Hz display, great for both gaming and everyday productivity tasks.",
        "stores": [
            {"store": "Amazon",          "price": 84999,  "url": "https://www.amazon.in/s?k=Acer+Nitro+16+RTX+4060+Ryzen+7&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 86999,  "url": "https://www.flipkart.com/search?q=Acer+Nitro+16+RTX+4060+Ryzen+7"},
            {"store": "Croma",           "price": 89999,  "url": "https://www.croma.com/searchB?q=Acer+Nitro+16+RTX+4060"},
            {"store": "Reliance Digital","price": 87999,  "url": "https://www.reliancedigital.in/search?q=Acer+Nitro+16+RTX+4060"},
            {"store": "Acer Store",      "price": 89999,  "url": "https://www.acer.com/in-en/laptops/nitro/nitro-16/"},
        ],
    },
    # MSI Katana (popular budget-mid gaming)
    {
        "brand": "MSI",
        "name": "MSI Katana 15 (RTX 4060)",
        "image_url": "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80",
        "cpu": "Intel Core i7-12650H",
        "cpu_score": 82,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "IPS",
        "refresh_rate": 144,
        "weight_kg": 2.2,
        "battery_wh": 53,
        "battery_score": 42,
        "thermal_score": 74,
        "base_price": 94999,
        "description": "MSI Katana 15 with RTX 4060 delivers solid gaming performance in a relatively portable chassis. Great value for mid-range gamers looking for a reliable daily driver.",
        "stores": [
            {"store": "Amazon",          "price": 88999,  "url": "https://www.amazon.in/s?k=MSI+Katana+15+RTX+4060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 91999,  "url": "https://www.flipkart.com/search?q=MSI+Katana+15+RTX+4060"},
            {"store": "Croma",           "price": 94999,  "url": "https://www.croma.com/searchB?q=MSI+Katana+15+RTX+4060"},
            {"store": "Reliance Digital","price": 92999,  "url": "https://www.reliancedigital.in/search?q=MSI+Katana+15+RTX+4060"},
            {"store": "MSI Store",       "price": 94999,  "url": "https://in.msi.com/Laptop/Katana-15-B12V"},
        ],
    },

    {
        "brand": "ASUS",
        "name": "ASUS ROG Strix G16 (2024)",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80",
        "cpu": "Intel Core i9-14900HX",
        "cpu_score": 92,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 1024,
        "display_inch": 16.0,
        "display_type": "IPS",
        "refresh_rate": 165,
        "weight_kg": 2.5,
        "battery_wh": 90,
        "battery_score": 55,
        "thermal_score": 80,
        "base_price": 139999,
        "description": "A powerhouse gaming laptop with Intel's latest 14th Gen processor and RTX 4060 GPU. Designed for high FPS gaming with excellent thermal performance.",
        "stores": [
            {"store": "Amazon",          "price": 134999, "url": "https://www.amazon.in/s?k=ASUS+ROG+Strix+G16+2024+RTX+4060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 136999, "url": "https://www.flipkart.com/search?q=ASUS+ROG+Strix+G16+RTX+4060"},
            {"store": "Croma",           "price": 139999, "url": "https://www.croma.com/searchB?q=ASUS+ROG+Strix+G16"},
            {"store": "Reliance Digital","price": 138999, "url": "https://www.reliancedigital.in/search?q=ASUS+ROG+Strix+G16"},
            {"store": "ASUS Store",      "price": 139999, "url": "https://www.asus.com/in/laptops/for-gaming/rog-strix/asus-rog-strix-g16/"},
        ],
    },
    {
        "brand": "Lenovo",
        "name": "Lenovo Legion Pro 5i Gen 9",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
        "cpu": "Intel Core i7-14700HX",
        "cpu_score": 88,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 16.0,
        "display_type": "IPS",
        "refresh_rate": 165,
        "weight_kg": 2.4,
        "battery_wh": 80,
        "battery_score": 50,
        "thermal_score": 82,
        "base_price": 124999,
        "description": "Lenovo's Legion Pro 5i offers exceptional gaming performance with Intel 14th Gen and RTX 4060, paired with a 165Hz high-refresh display.",
        "stores": [
            {"store": "Amazon",          "price": 119999, "url": "https://www.amazon.in/s?k=Lenovo+Legion+Pro+5i+Gen+9+RTX+4060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 121999, "url": "https://www.flipkart.com/search?q=Lenovo+Legion+Pro+5i+Gen+9"},
            {"store": "Croma",           "price": 124999, "url": "https://www.croma.com/searchB?q=Lenovo+Legion+Pro+5i"},
            {"store": "Reliance Digital","price": 122999, "url": "https://www.reliancedigital.in/search?q=Lenovo+Legion+Pro+5i+Gen+9"},
            {"store": "Lenovo Store",    "price": 124999, "url": "https://www.lenovo.com/in/en/laptops/legion-laptops/legion-pro-5-series/"},
        ],
    },
    {
        "brand": "Apple",
        "name": "Apple MacBook Pro 14\" M3 Pro",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
        "cpu": "Apple M3 Pro (11-core)",
        "cpu_score": 90,
        "gpu": "Apple M3 Pro 14-core GPU",
        "gpu_score": 80,
        "ram_gb": 18,
        "storage_gb": 512,
        "display_inch": 14.2,
        "display_type": "OLED",
        "refresh_rate": 120,
        "weight_kg": 1.6,
        "battery_wh": 70,
        "battery_score": 95,
        "thermal_score": 85,
        "base_price": 199990,
        "description": "The MacBook Pro 14 with M3 Pro delivers exceptional performance and battery life, featuring a stunning Liquid Retina XDR display perfect for creatives and developers.",
        "stores": [
            {"store": "Amazon",          "price": 194900, "url": "https://www.amazon.in/s?k=Apple+MacBook+Pro+14+M3+Pro&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 196990, "url": "https://www.flipkart.com/search?q=Apple+MacBook+Pro+14+M3+Pro"},
            {"store": "Croma",           "price": 199990, "url": "https://www.croma.com/searchB?q=MacBook+Pro+14+M3+Pro"},
            {"store": "Reliance Digital","price": 199990, "url": "https://www.reliancedigital.in/search?q=MacBook+Pro+14+M3+Pro"},
            {"store": "Apple Store",     "price": 199990, "url": "https://www.apple.com/in/shop/buy-mac/macbook-pro/14-inch"},
        ],
    },
    {
        "brand": "Dell",
        "name": "Dell XPS 15 (9530)",
        "image_url": "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
        "cpu": "Intel Core i7-13700H",
        "cpu_score": 84,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "OLED",
        "refresh_rate": 60,
        "weight_kg": 1.86,
        "battery_wh": 86,
        "battery_score": 70,
        "thermal_score": 72,
        "base_price": 179990,
        "description": "The Dell XPS 15 combines stunning OLED display quality with solid GPU performance in an ultra-premium, thin chassis ideal for video editors and creators.",
        "stores": [
            {"store": "Amazon",          "price": 172990, "url": "https://www.amazon.in/s?k=Dell+XPS+15+9530+RTX+4060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 174990, "url": "https://www.flipkart.com/search?q=Dell+XPS+15+9530"},
            {"store": "Croma",           "price": 179990, "url": "https://www.croma.com/searchB?q=Dell+XPS+15+9530"},
            {"store": "Reliance Digital","price": 177990, "url": "https://www.reliancedigital.in/search?q=Dell+XPS+15"},
            {"store": "Dell Store",      "price": 179990, "url": "https://www.dell.com/en-in/shop/laptops/xps-15-laptop/spd/xps-15-9530-laptop"},
        ],
    },
    {
        "brand": "HP",
        "name": "HP Spectre x360 14",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80",
        "cpu": "Intel Core Ultra 7 155H",
        "cpu_score": 82,
        "gpu": "Intel Arc Graphics",
        "gpu_score": 45,
        "ram_gb": 16,
        "storage_gb": 1024,
        "display_inch": 14.0,
        "display_type": "OLED",
        "refresh_rate": 120,
        "weight_kg": 1.42,
        "battery_wh": 66,
        "battery_score": 88,
        "thermal_score": 70,
        "base_price": 159999,
        "description": "HP's flagship convertible with a gorgeous OLED touchscreen, ultra-thin design, and Intel's latest AI-powered processors for everyday productivity.",
        "stores": [
            {"store": "Amazon",          "price": 152999, "url": "https://www.amazon.in/s?k=HP+Spectre+x360+14+2024&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 154999, "url": "https://www.flipkart.com/search?q=HP+Spectre+x360+14"},
            {"store": "Croma",           "price": 159999, "url": "https://www.croma.com/searchB?q=HP+Spectre+x360+14"},
            {"store": "Reliance Digital","price": 157999, "url": "https://www.reliancedigital.in/search?q=HP+Spectre+x360"},
            {"store": "HP Store",        "price": 159999, "url": "https://www.hp.com/in-en/shop/pdp/hp-spectre-x360-14-eu0058tu"},
        ],
    },
    {
        "brand": "ASUS",
        "name": "ASUS ProArt Studiobook 16",
        "image_url": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
        "cpu": "Intel Core i9-13980HX",
        "cpu_score": 91,
        "gpu": "NVIDIA RTX 4070",
        "gpu_score": 90,
        "ram_gb": 32,
        "storage_gb": 1024,
        "display_inch": 16.0,
        "display_type": "OLED",
        "refresh_rate": 60,
        "weight_kg": 1.85,
        "battery_wh": 90,
        "battery_score": 60,
        "thermal_score": 78,
        "base_price": 229999,
        "description": "The ProArt Studiobook 16 is built for creative professionals with an OLED ProArt display, RTX 4070, and 32GB RAM for seamless 3D rendering and video editing.",
        "stores": [
            {"store": "Amazon",          "price": 218999, "url": "https://www.amazon.in/s?k=ASUS+ProArt+Studiobook+16+RTX+4070&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 222999, "url": "https://www.flipkart.com/search?q=ASUS+ProArt+Studiobook+16"},
            {"store": "Croma",           "price": 229999, "url": "https://www.croma.com/searchB?q=ASUS+ProArt+Studiobook+16"},
            {"store": "Reliance Digital","price": 226999, "url": "https://www.reliancedigital.in/search?q=ASUS+ProArt+Studiobook+16"},
            {"store": "ASUS Store",      "price": 229999, "url": "https://www.asus.com/in/laptops/for-creators/proart-studiobook/asus-proart-studiobook-16-h7604/"},
        ],
    },
    {
        "brand": "Lenovo",
        "name": "ThinkPad X1 Carbon Gen 12",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80",
        "cpu": "Intel Core Ultra 7 164U",
        "cpu_score": 78,
        "gpu": "Intel Graphics",
        "gpu_score": 38,
        "ram_gb": 32,
        "storage_gb": 1024,
        "display_inch": 14.0,
        "display_type": "IPS",
        "refresh_rate": 60,
        "weight_kg": 1.12,
        "battery_wh": 57,
        "battery_score": 92,
        "thermal_score": 75,
        "base_price": 189999,
        "description": "The ThinkPad X1 Carbon is the ultimate business ultrabook — featherlight at 1.12kg, with class-leading battery life, legendary keyboard, and enterprise-grade security.",
        "stores": [
            {"store": "Amazon",          "price": 179999, "url": "https://www.amazon.in/s?k=Lenovo+ThinkPad+X1+Carbon+Gen+12&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 182999, "url": "https://www.flipkart.com/search?q=Lenovo+ThinkPad+X1+Carbon+Gen+12"},
            {"store": "Croma",           "price": 189999, "url": "https://www.croma.com/searchB?q=ThinkPad+X1+Carbon+Gen+12"},
            {"store": "Reliance Digital","price": 186999, "url": "https://www.reliancedigital.in/search?q=ThinkPad+X1+Carbon+Gen+12"},
            {"store": "Lenovo Store",    "price": 189999, "url": "https://www.lenovo.com/in/en/laptops/thinkpad/thinkpad-x1/thinkpad-x1-carbon-gen-12/"},
        ],
    },
    {
        "brand": "MSI",
        "name": "MSI Titan GT77 HX",
        "image_url": "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80",
        "cpu": "Intel Core i9-13980HX",
        "cpu_score": 94,
        "gpu": "NVIDIA RTX 4090",
        "gpu_score": 98,
        "ram_gb": 64,
        "storage_gb": 2048,
        "display_inch": 17.3,
        "display_type": "IPS",
        "refresh_rate": 240,
        "weight_kg": 3.3,
        "battery_wh": 99,
        "battery_score": 35,
        "thermal_score": 88,
        "base_price": 369999,
        "description": "The MSI Titan GT77 is an absolute beast — desktop-class RTX 4090 in a laptop chassis with 240Hz display for the most demanding games and AI workloads.",
        "stores": [
            {"store": "Amazon",          "price": 354999, "url": "https://www.amazon.in/s?k=MSI+Titan+GT77+HX+RTX+4090&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 358999, "url": "https://www.flipkart.com/search?q=MSI+Titan+GT77+HX+RTX+4090"},
            {"store": "Croma",           "price": 369999, "url": "https://www.croma.com/searchB?q=MSI+Titan+GT77"},
            {"store": "Reliance Digital","price": 364999, "url": "https://www.reliancedigital.in/search?q=MSI+Titan+GT77"},
            {"store": "MSI Store",       "price": 369999, "url": "https://in.msi.com/Laptop/Titan-GT77-HX-13V"},
        ],
    },
    {
        "brand": "Acer",
        "name": "Acer Predator Helios Neo 16",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80",
        "cpu": "Intel Core i7-13700HX",
        "cpu_score": 86,
        "gpu": "NVIDIA RTX 4050",
        "gpu_score": 75,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 16.0,
        "display_type": "IPS",
        "refresh_rate": 165,
        "weight_kg": 2.5,
        "battery_wh": 76,
        "battery_score": 48,
        "thermal_score": 75,
        "base_price": 89999,
        "description": "Acer's Predator Helios Neo offers superb gaming performance at a competitive price point with RTX 4050 graphics and a 165Hz IPS display.",
        "stores": [
            {"store": "Amazon",          "price": 84999,  "url": "https://www.amazon.in/s?k=Acer+Predator+Helios+Neo+16+RTX+4050&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 86999,  "url": "https://www.flipkart.com/search?q=Acer+Predator+Helios+Neo+16"},
            {"store": "Croma",           "price": 89999,  "url": "https://www.croma.com/searchB?q=Acer+Predator+Helios+Neo+16"},
            {"store": "Reliance Digital","price": 88999,  "url": "https://www.reliancedigital.in/search?q=Acer+Predator+Helios+Neo+16"},
            {"store": "Acer Store",      "price": 89999,  "url": "https://www.acer.com/in-en/laptops/predator/predator-helios-neo-16/"},
        ],
    },
    {
        "brand": "Samsung",
        "name": "Samsung Galaxy Book4 Pro 360",
        "image_url": "https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&q=80",
        "cpu": "Intel Core Ultra 7 155H",
        "cpu_score": 82,
        "gpu": "Intel Arc Graphics",
        "gpu_score": 46,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 16.0,
        "display_type": "AMOLED",
        "refresh_rate": 120,
        "weight_kg": 1.66,
        "battery_wh": 76,
        "battery_score": 80,
        "thermal_score": 70,
        "base_price": 149990,
        "description": "The Galaxy Book4 Pro 360 is Samsung's premium 2-in-1 with a brilliant 3K AMOLED touchscreen, S-Pen support, and seamless Galaxy ecosystem integration.",
        "stores": [
            {"store": "Amazon",          "price": 142990, "url": "https://www.amazon.in/s?k=Samsung+Galaxy+Book4+Pro+360&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 144990, "url": "https://www.flipkart.com/search?q=Samsung+Galaxy+Book4+Pro+360"},
            {"store": "Croma",           "price": 149990, "url": "https://www.croma.com/searchB?q=Samsung+Galaxy+Book4+Pro+360"},
            {"store": "Reliance Digital","price": 146990, "url": "https://www.reliancedigital.in/search?q=Samsung+Galaxy+Book4+Pro+360"},
            {"store": "Samsung Store",   "price": 149990, "url": "https://www.samsung.com/in/computers/galaxy-book/galaxy-book4-pro-360-16-np960qed-kb1in/"},
        ],
    },
    {
        "brand": "ASUS",
        "name": "ASUS TUF Gaming A15 (2024)",
        "image_url": "https://images.unsplash.com/photo-1607706189992-eae578626c86?w=800&q=80",
        "cpu": "AMD Ryzen 9 7945HX",
        "cpu_score": 89,
        "gpu": "NVIDIA RTX 4060",
        "gpu_score": 85,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.6,
        "display_type": "IPS",
        "refresh_rate": 144,
        "weight_kg": 2.2,
        "battery_wh": 90,
        "battery_score": 58,
        "thermal_score": 77,
        "base_price": 99999,
        "description": "ASUS TUF Gaming A15 with Ryzen 9 and RTX 4060 offers excellent value for gamers who need power without breaking the bank.",
        "stores": [
            {"store": "Amazon",          "price": 94999,  "url": "https://www.amazon.in/s?k=ASUS+TUF+Gaming+A15+2024+RTX+4060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 96999,  "url": "https://www.flipkart.com/search?q=ASUS+TUF+Gaming+A15+RTX+4060"},
            {"store": "Croma",           "price": 99999,  "url": "https://www.croma.com/searchB?q=ASUS+TUF+Gaming+A15+2024"},
            {"store": "Reliance Digital","price": 97999,  "url": "https://www.reliancedigital.in/search?q=ASUS+TUF+Gaming+A15+2024"},
            {"store": "ASUS Store",      "price": 99999,  "url": "https://www.asus.com/in/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-a15/"},
        ],
    },
    {
        "brand": "Microsoft",
        "name": "Microsoft Surface Laptop 6",
        "image_url": "https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=800&q=80",
        "cpu": "Intel Core Ultra 5 135H",
        "cpu_score": 79,
        "gpu": "Intel Arc Graphics",
        "gpu_score": 44,
        "ram_gb": 16,
        "storage_gb": 256,
        "display_inch": 13.5,
        "display_type": "IPS",
        "refresh_rate": 60,
        "weight_kg": 1.34,
        "battery_wh": 54,
        "battery_score": 85,
        "thermal_score": 72,
        "base_price": 119999,
        "description": "Microsoft's sleek Surface Laptop 6 features a gorgeous PixelSense display, premium build quality, and excellent battery life for students and professionals.",
        "stores": [
            {"store": "Amazon",          "price": 113999, "url": "https://www.amazon.in/s?k=Microsoft+Surface+Laptop+6&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 115999, "url": "https://www.flipkart.com/search?q=Microsoft+Surface+Laptop+6"},
            {"store": "Croma",           "price": 119999, "url": "https://www.croma.com/searchB?q=Microsoft+Surface+Laptop+6"},
            {"store": "Reliance Digital","price": 117999, "url": "https://www.reliancedigital.in/search?q=Microsoft+Surface+Laptop+6"},
            {"store": "Microsoft Store", "price": 119999, "url": "https://www.microsoft.com/en-in/d/surface-laptop-6/8pnmcd3qr4jn"},
        ],
    },
    {
        "brand": "Lenovo",
        "name": "Lenovo IdeaPad Slim 5 (2024)",
        "image_url": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
        "cpu": "AMD Ryzen 7 7730U",
        "cpu_score": 70,
        "gpu": "AMD Radeon 780M",
        "gpu_score": 40,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 14.0,
        "display_type": "IPS",
        "refresh_rate": 60,
        "weight_kg": 1.46,
        "battery_wh": 60,
        "battery_score": 82,
        "thermal_score": 68,
        "base_price": 59999,
        "description": "The IdeaPad Slim 5 is a well-rounded mid-range laptop for students with solid battery life, a light chassis, and capable Ryzen 7 performance.",
        "stores": [
            {"store": "Amazon",          "price": 54999,  "url": "https://www.amazon.in/s?k=Lenovo+IdeaPad+Slim+5+2024+Ryzen+7&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 56999,  "url": "https://www.flipkart.com/search?q=Lenovo+IdeaPad+Slim+5+2024"},
            {"store": "Croma",           "price": 59999,  "url": "https://www.croma.com/searchB?q=Lenovo+IdeaPad+Slim+5+2024"},
            {"store": "Reliance Digital","price": 57999,  "url": "https://www.reliancedigital.in/search?q=Lenovo+IdeaPad+Slim+5+2024"},
            {"store": "Lenovo Store",    "price": 59999,  "url": "https://www.lenovo.com/in/en/laptops/ideapad/ideapad-slim-5/"},
        ],
    },
    {
        "brand": "HP",
        "name": "HP Victus 16 (2024)",
        "image_url": "https://images.unsplash.com/photo-1553355552-9808ef857c01?w=800&q=80",
        "cpu": "AMD Ryzen 7 7745HX",
        "cpu_score": 83,
        "gpu": "NVIDIA RTX 4050",
        "gpu_score": 75,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 16.1,
        "display_type": "IPS",
        "refresh_rate": 144,
        "weight_kg": 2.29,
        "battery_wh": 70,
        "battery_score": 52,
        "thermal_score": 72,
        "base_price": 79999,
        "description": "HP Victus 16 is a budget-friendly gaming laptop with RTX 4050 and a crisp 144Hz display, offering great value for casual gamers.",
        "stores": [
            {"store": "Amazon",          "price": 74999,  "url": "https://www.amazon.in/s?k=HP+Victus+16+RTX+4050+2024&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 76999,  "url": "https://www.flipkart.com/search?q=HP+Victus+16+RTX+4050+2024"},
            {"store": "Croma",           "price": 79999,  "url": "https://www.croma.com/searchB?q=HP+Victus+16+2024"},
            {"store": "Reliance Digital","price": 77999,  "url": "https://www.reliancedigital.in/search?q=HP+Victus+16+2024"},
            {"store": "HP Store",        "price": 79999,  "url": "https://www.hp.com/in-en/shop/pdp/hp-victus-16-r0097tx"},
        ],
    },
    {
        "brand": "Razer",
        "name": "Razer Blade 16 (2024)",
        "image_url": "https://images.unsplash.com/photo-1619441207978-3d326c46e2c9?w=800&q=80",
        "cpu": "Intel Core i9-14900HX",
        "cpu_score": 93,
        "gpu": "NVIDIA RTX 4090",
        "gpu_score": 98,
        "ram_gb": 32,
        "storage_gb": 1024,
        "display_inch": 16.0,
        "display_type": "OLED",
        "refresh_rate": 240,
        "weight_kg": 2.14,
        "battery_wh": 95,
        "battery_score": 55,
        "thermal_score": 85,
        "base_price": 399999,
        "description": "The Razer Blade 16 is the pinnacle of gaming laptop design — RTX 4090, dual-mode 240Hz OLED display, and CNC aluminum chassis in a remarkably slim 16-inch package.",
        "stores": [
            {"store": "Amazon",          "price": 384999, "url": "https://www.amazon.in/s?k=Razer+Blade+16+2024+RTX+4090&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 389999, "url": "https://www.flipkart.com/search?q=Razer+Blade+16+RTX+4090"},
            {"store": "Croma",           "price": 399999, "url": "https://www.croma.com/searchB?q=Razer+Blade+16"},
            {"store": "Reliance Digital","price": 394999, "url": "https://www.reliancedigital.in/search?q=Razer+Blade+16+2024"},
            {"store": "Razer Store",     "price": 399999, "url": "https://www.razer.com/gaming-laptops/razer-blade-16"},
        ],
    },
    {
        "brand": "Apple",
        "name": "Apple MacBook Air 15\" M3",
        "image_url": "https://images.unsplash.com/photo-1593642632634-9cf8ecf35f7a?w=800&q=80",
        "cpu": "Apple M3 (8-core)",
        "cpu_score": 82,
        "gpu": "Apple M3 10-core GPU",
        "gpu_score": 68,
        "ram_gb": 16,
        "storage_gb": 512,
        "display_inch": 15.3,
        "display_type": "IPS",
        "refresh_rate": 60,
        "weight_kg": 1.51,
        "battery_wh": 66,
        "battery_score": 96,
        "thermal_score": 80,
        "base_price": 149900,
        "description": "The MacBook Air 15 M3 is the ultimate productivity laptop — near-silent fanless design, all-day 18-hour battery, and a huge bright display in a featherweight chassis.",
        "stores": [
            {"store": "Amazon",          "price": 144900, "url": "https://www.amazon.in/s?k=Apple+MacBook+Air+15+M3&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 146900, "url": "https://www.flipkart.com/search?q=Apple+MacBook+Air+15+M3"},
            {"store": "Croma",           "price": 149900, "url": "https://www.croma.com/searchB?q=MacBook+Air+15+M3"},
            {"store": "Reliance Digital","price": 148900, "url": "https://www.reliancedigital.in/search?q=MacBook+Air+15+M3"},
            {"store": "Apple Store",     "price": 149900, "url": "https://www.apple.com/in/shop/buy-mac/macbook-air/15-inch"},
        ],
    },
    # ── RTX 50-series ──────────────────────────────────────────────────────────
    {
        "brand": "ASUS",
        "name": "ASUS ROG Strix G18 (RTX 5060)",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80",
        "cpu": "Intel Core i9-14900HX",
        "cpu_score": 93,
        "gpu": "NVIDIA RTX 5060",
        "gpu_score": 91,
        "ram_gb": 16,
        "storage_gb": 1024,
        "display_inch": 18.0,
        "display_type": "IPS",
        "refresh_rate": 240,
        "weight_kg": 3.1,
        "battery_wh": 90,
        "battery_score": 45,
        "thermal_score": 83,
        "base_price": 169999,
        "description": "ASUS ROG Strix G18 with the next-gen RTX 5060 delivers a massive leap in rasterisation and ray tracing performance over the 40-series at a mid-range price.",
        "stores": [
            {"store": "Amazon",          "price": 159999, "url": "https://www.amazon.in/s?k=ASUS+ROG+Strix+G18+RTX+5060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 162999, "url": "https://www.flipkart.com/search?q=ASUS+ROG+Strix+G18+RTX+5060"},
            {"store": "Croma",           "price": 169999, "url": "https://www.croma.com/searchB?q=ASUS+ROG+Strix+G18+RTX+5060"},
            {"store": "Reliance Digital","price": 165999, "url": "https://www.reliancedigital.in/search?q=ASUS+ROG+Strix+G18+RTX+5060"},
            {"store": "ASUS Store",      "price": 169999, "url": "https://www.asus.com/in/laptops/for-gaming/rog-strix/asus-rog-strix-g18/"},
        ],
    },
    {
        "brand": "Lenovo",
        "name": "Lenovo Legion 5i Gen 10 (RTX 5060)",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
        "cpu": "Intel Core Ultra 9 285HX",
        "cpu_score": 95,
        "gpu": "NVIDIA RTX 5060",
        "gpu_score": 91,
        "ram_gb": 32,
        "storage_gb": 1024,
        "display_inch": 16.0,
        "display_type": "IPS",
        "refresh_rate": 165,
        "weight_kg": 2.4,
        "battery_wh": 80,
        "battery_score": 52,
        "thermal_score": 84,
        "base_price": 154999,
        "description": "The Legion 5i Gen 10 pairs Intel's flagship Ultra 9 285HX with the RTX 5060 for a next-generation gaming experience at a compelling price point.",
        "stores": [
            {"store": "Amazon",          "price": 146999, "url": "https://www.amazon.in/s?k=Lenovo+Legion+5i+Gen+10+RTX+5060&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 149999, "url": "https://www.flipkart.com/search?q=Lenovo+Legion+5i+Gen+10+RTX+5060"},
            {"store": "Croma",           "price": 154999, "url": "https://www.croma.com/searchB?q=Lenovo+Legion+5i+Gen+10"},
            {"store": "Reliance Digital","price": 151999, "url": "https://www.reliancedigital.in/search?q=Lenovo+Legion+5i+Gen+10+RTX+5060"},
            {"store": "Lenovo Store",    "price": 154999, "url": "https://www.lenovo.com/in/en/laptops/legion-laptops/legion-5-series/"},
        ],
    },
    {
        "brand": "MSI",
        "name": "MSI Raider GE78 HX (RTX 5080)",
        "image_url": "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80",
        "cpu": "Intel Core i9-14900HX",
        "cpu_score": 94,
        "gpu": "NVIDIA RTX 5080",
        "gpu_score": 96,
        "ram_gb": 32,
        "storage_gb": 2048,
        "display_inch": 17.3,
        "display_type": "IPS",
        "refresh_rate": 240,
        "weight_kg": 2.9,
        "battery_wh": 99,
        "battery_score": 38,
        "thermal_score": 89,
        "base_price": 329999,
        "description": "MSI Raider GE78 HX with RTX 5080 is a next-gen powerhouse built for 4K gaming and heavy AI/ML tasks, offering near-desktop GPU performance.",
        "stores": [
            {"store": "Amazon",          "price": 312999, "url": "https://www.amazon.in/s?k=MSI+Raider+GE78+RTX+5080&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 318999, "url": "https://www.flipkart.com/search?q=MSI+Raider+GE78+RTX+5080"},
            {"store": "Croma",           "price": 329999, "url": "https://www.croma.com/searchB?q=MSI+Raider+GE78+RTX+5080"},
            {"store": "Reliance Digital","price": 323999, "url": "https://www.reliancedigital.in/search?q=MSI+Raider+GE78+RTX+5080"},
            {"store": "MSI Store",       "price": 329999, "url": "https://in.msi.com/Laptop/Raider-GE78-HX-14V"},
        ],
    },
    {
        "brand": "ASUS",
        "name": "ASUS ROG Zephyrus G16 (RTX 5090)",
        "image_url": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
        "cpu": "AMD Ryzen AI 9 HX 370",
        "cpu_score": 96,
        "gpu": "NVIDIA RTX 5090",
        "gpu_score": 100,
        "ram_gb": 64,
        "storage_gb": 2048,
        "display_inch": 16.0,
        "display_type": "OLED",
        "refresh_rate": 240,
        "weight_kg": 2.0,
        "battery_wh": 90,
        "battery_score": 50,
        "thermal_score": 90,
        "base_price": 499999,
        "description": "The ROG Zephyrus G16 with RTX 5090 is the ultimate next-gen gaming laptop — flagship GPU, OLED 240Hz display, and AMD's most powerful mobile chip in a sleek chassis.",
        "stores": [
            {"store": "Amazon",          "price": 479999, "url": "https://www.amazon.in/s?k=ASUS+ROG+Zephyrus+G16+RTX+5090&tag=laptopmind-21"},
            {"store": "Flipkart",        "price": 484999, "url": "https://www.flipkart.com/search?q=ASUS+ROG+Zephyrus+G16+RTX+5090"},
            {"store": "Croma",           "price": 499999, "url": "https://www.croma.com/searchB?q=ASUS+ROG+Zephyrus+G16+RTX+5090"},
            {"store": "Reliance Digital","price": 492999, "url": "https://www.reliancedigital.in/search?q=ASUS+ROG+Zephyrus+G16+RTX+5090"},
            {"store": "ASUS Store",      "price": 499999, "url": "https://www.asus.com/in/laptops/for-gaming/rog-zephyrus/asus-rog-zephyrus-g16/"},
        ],
    },
]


def seed():
    db = SessionLocal()
    try:
        db.query(PriceHistory).delete()
        db.query(StorePrice).delete()
        db.query(Laptop).delete()
        db.commit()

        for data in LAPTOPS:
            stores = data.pop("stores")
            laptop = Laptop(**data)
            db.add(laptop)
            db.flush()

            min_price = min(s["price"] for s in stores)
            for s in stores:
                sp = StorePrice(
                    laptop_id=laptop.id,
                    store_name=s["store"],
                    price=s["price"],
                    url=s["url"],
                    is_lowest=(s["price"] == min_price),
                )
                db.add(sp)

            # 90-day Amazon price history
            today = datetime.date.today()
            amazon_store = next(s for s in stores if s["store"] == "Amazon")
            base = amazon_store["price"]
            for day_offset in range(90, -1, -1):
                date = today - datetime.timedelta(days=day_offset)
                fluctuation = random.uniform(-0.08, 0.05)
                price = int(base * (1 + fluctuation))
                ph = PriceHistory(
                    laptop_id=laptop.id,
                    store_name="Amazon",
                    price=price,
                    recorded_at=date,
                )
                db.add(ph)

        db.commit()
        print(f"✅ Seeded {len(LAPTOPS)} laptops with store prices and price history!")
    except Exception as e:
        db.rollback()
        print(f"❌ Error seeding: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
